Init Commit
verbusharas/BankingSystem-2- pull request #1
Opened 2020-09-30 07:10 UTC by verbusharas

@Elvinasl please review.

2020-09-30 20:31 UTC, pavelvrublevskij requested changes
Pakoreguok .gitignore: nekelk target aplanko. Istriniau tam tikrus failus, per daug rode :)
Toliau laukiu korekciju. Po korekciju pratesiu review.

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/App.java
> +import lt.verbus.repository.*;
nenaudojam wildcard, rodom visas naudojamas klases

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/config/CreditInterest.java
> +    public static final double percent = 4;
Constantos pagal Java convention rasom didziosiom raidem.

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/controller/Controller.java
> +import lt.verbus.view.*;
wildcards, nenaudojam

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/App.java
> +        ConnectionPool.closeConnections();
Panasu kad nereikalingas. Nematau teisingo kitose klasese panaudojimo.

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/exception/InsufficientFundsException.java
> +    public InsufficientFundsException(String message) {
Nelipdome metodus, do as new line :)

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/repository/BankAccountRepository.java
> +import java.sql.*;
wildcards pakeiciam i naudojamas klases

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/repository/GenericRepository.java
> +public abstract class GenericRepository<T> {
uz Generic panaudojima 10 balu

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/repository/ConnectionPool.java
> +public class ConnectionPool {
Tokia klase turi buti final ir tureti private konstruktoriu

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/controller/Controller.java
> +        creditRepository = new CreditRepository(ConnectionPool.getConnection(SqlDialect.MY_SQL));
ConnectionPool galima aprasyti GenericRepository ir Controller klaseje visikai ismesti is import'o

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/controller/Controller.java
> +        bankRepository = new BankRepository(ConnectionPool.getConnection(SqlDialect.MY_SQL));
Dialect turi buti aprasytas properties prie bazes. Tai yra bazes konfiguracine dalis

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/controller/Controller.java
> +    private CreditService creditService;
Labai daug visko vienoje klaseje. Gal repositorijas iskelti i atitinkamus servisus, tada nebus tokio chaoso Controlleri?

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/controller/Controller.java
> +                    ListPrinter.printNumeratedListToConsole(bankAccountRepository.findAllBelongingTo(currentUser));
Padaryk per servisa ir bus labai gerai

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/controller/Controller.java
> +    }
Labai yra kodo panasumu (dubliuojasi), tikrai galima padaryti geriau sitoje vietoje. Leidziu pagalvoti ir parefaktorint.

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/controller/Controller.java
> +                }
Islygiuojam, kazkaip nuvaziavo :)

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/repository/BankAccountRepository.java
> +        if (object instanceof User) {
Jei kode naudojamas instanceof tai toki koda galima pakoreguoti ir padaryti be. Siulau sukurti du skirtingus metodus panaikinant generic Object parametra nurodant tikslaiai klase, o pati Select'a iskelti i konstanta.

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/repository/BankAccountRepository.java
> +        String query = ("SELECT * FROM bank_account WHERE ");
`bank_account `pas tave jau perduotas per super Generic klasei? kodel tada kartoji n kartu esamoje klaseje?

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/view/ListPrinter.java
> +            }
`list.forEach(t -> {`

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/services/CreditService.java
> +        if (sender != null) {
Ifus iskeliam i atskirus metodus, pvz.: `upadteSenderCredits`, `updateReceiverCredits`

2020-09-30 20:31 UTC, pavelvrublevskij commented on src/main/java/lt/verbus/repository/CreditRepository.java
> +    }
Nereikia tokiu metodu. Gali drasiai is esamu repositor klasiu trinti i viskas veiks (GenericRepository svarbiausia palik).

2020-10-01 21:15 UTC, verbusharas commented
@pavelvrublevskij klaidas, regis, ištaisiau.

2020-10-06 07:02 UTC, Elvinasl approved these changes
Sauniai padirbeta, yra kur tobuleti!

2020-10-06 07:02 UTC, Elvinasl commented on bootstrap_banking_system_database.sql
> +-- POPULATE USERS
At atskirciau create ir seed sql. 

Create - apraso tavo DB struktura, to visada reikia.

Seed - prikrauna tavo DB duomenimis. Ar to visada reikia?

2020-10-06 07:02 UTC, Elvinasl commented on pom.xml
> +      <version>8.0.21</version>
Ar zinojai kad versijas galima apsirasyti i kintamuosius ir nurodyti virsuje?

2020-10-06 07:02 UTC, Elvinasl commented on src/main/java/lt/verbus/controller/Controller.java
> +    }
Ar nemanai kad vienas kontroleris patapo siek tiek per didelis? Gal butu protinga ji isskirstyti? BankController, UserController etc.?

2020-10-06 07:02 UTC, Elvinasl commented on src/main/java/lt/verbus/controller/Controller.java
> +        while (true) {
infinite loop? procesorius nepradeda garsiai uzti? :))

2020-10-06 07:02 UTC, Elvinasl commented on src/main/java/lt/verbus/controller/Controller.java
> +            Messenger.Error.warnAboutUserExists();
Sita funkcija visada issaukiama, ar toks buvo tikslas?

2020-10-06 07:02 UTC, Elvinasl commented on src/main/java/lt/verbus/controller/Controller.java
> +        boolean stayInMenu = true;
O ar tikrai to mums reikia visur? Galbut galima sugalvoti kazkokia funkcija pvz toggleMenu() {
stayInMenu = !stayInMenu; 
}

?

2020-10-06 07:02 UTC, Elvinasl commented on src/main/java/lt/verbus/model/BankAccount.java
> +    private User holder;
kodel pakeiti is User -> holder. Kuo toliau tuo labiau confusing bus?

2020-10-06 07:02 UTC, Elvinasl commented on src/main/java/lt/verbus/repository/GenericRepository.java
> +
Labai liuks!

2020-10-06 07:02 UTC, Elvinasl commented on src/main/java/lt/verbus/repository/TransactionRepository.java
> +        }
Man keistai repositorijos klasej matyt tokia logika

2020-10-06 07:02 UTC, Elvinasl commented on src/main/java/lt/verbus/view/Menu.java
> +
Labai daug inner statiniu klasiu. Isskaidyti reiketu

2020-10-06 07:02 UTC, Elvinasl commented on src/main/java/lt/verbus/view/Messenger.java
> +    }
Vel labai nestinam statines klases. Koks tikslas? As nesutikciau su tokia logika. Tada gal geriau loggeri naudot? Galbut galim perduoti message tipa? 

Dabar cia nustatome tik spalva, del to skiriame i atskiras klases? Jeigu error = visada raudona, gal uztektu metodo?

2020-11-27 18:21 UTC, merged